baseURL = "https://amireyal5.netlify.app/"
title =  "עמיר אייל פסיכותרפיה מתבגרים, מבוגרים והדרכת הורים"
languageCode = "he"
defaultContentLanguage = "he"
defaultContentLanguageInSubdir = false
ignoreLogs = ['warning-goldmark-raw-html']

[Pagination]
  pagerSize = 10

theme = "tella"

[params]
  description = "הבלוג האישי שלי על כל דבר"
  opengraph = true
  twitter_cards = false
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["blog"]  # מחקתי את הערך הכפול של mainSections
  showBlog = true
  googleFonts = true

  myEmail = "amir@amireyal.co.il"
  myPhone = "+972547509962"
  myWhatsapp = "https://wa.me/972547509962"
  myLinkedin = "https://www.linkedin.com/in/amireyalprofile"
  myGithub = "https://github.com/amireyalusername"
  myRss = true

  [params.author]
    name = "עמיר אייל"
    bio = "פסיכותרפיסט מוסמך למתבגרים, מבוגרים והורים"
    avatar = "img/avatar-amir.jpg"

  [params.logo]
    main = "img/logo/logo.webp"
    alt = "עמיר אייל פסיכותרפיה לוגו"
    size = "h-14"

  [params.site]
    name = "Tella"

  [params.icon]
    fontawesome = true

[params.homepage_meta_tags]
  meta_description = "עמיר אייל - פסיכותרפיה לבוגרים, מתבגרים והדרכת הורים. טיפול מקצועי מותאם אישית."
  meta_og_title = "עמיר אייל | פסיכותרפיה למבוגרים ומתבגרים, הדרכת הורים"
  meta_og_type = "website"
  meta_og_url = "https://amireyal.co.il"
  meta_og_image = "https://amireyal.co.il/images/og-image.png"
  meta_og_description = "טיפול פסיכותרפי מקצועי לבוגרים, מתבגרים והדרכת הורים – עמיר אייל."

languageDirection = "rtl"

[menu]

  [[menu.main]]
    identifier = "faq"
    name = "שאלות נפוצות"
    url = "/faq/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "בלוג"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "אודות"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "צרו קשר"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    identifier = "home"
    name = "בית"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
    weight = 2
