baseURL = "https://amireyal5.netlify.app/"
title = "עמיר אייל פסיכותרפיה מתבגרים, מבוגרים והדרכת הורים"
languageCode = "he"
defaultContentLanguage = "he"
defaultContentLanguageInSubdir = false
ignoreLogs = ['warning-goldmark-raw-html']

[Pagination]
  pagerSize = 10

theme = "tella"

[params]
  description = "הבלוג האישי שלי על כל דבר"
  opengraph = true
  twitter_cards = false
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["blog"] # מחקתי את הערך הכפול של mainSections
  showBlog = true
  googleFonts = true

  myEmail = "amir@amireyal.co.il"
  myPhone = "+972547509962"
  myWhatsapp = "https://wa.me/972547509962"
  myLinkedin = "https://www.linkedin.com/in/amireyalprofile"
  myGithub = "https://github.com/amireyalusername"
  myRss = true

  [params.author]
    name = "עמיר אייל"
    bio = "פסיכותרפיסט מוסמך למתבגרים, מבוגרים והורים"
    avatar = "img/avatar-amir.jpg"

  [params.logo]
    main = "img/logo/logo.webp"
    alt = "עמיר אייל פסיכותרפיה לוגו"
    size = "h-14"

  [params.site]
    name = "Tella"

  [params.icon]
    fontawesome = true

[params.homepage_meta_tags]
  meta_description = "עמיר אייל - פסיכותרפיה לבוגרים, מתבגרים והדרכת הורים. טיפול מקצועי מותאם אישית."
  meta_og_title = "עמיר אייל | פסיכותרפיה למבוגרים ומתבגרים, הדרכת הורים"
  meta_og_type = "website"
  meta_og_url = "https://amireyal.co.il"
  meta_og_image = "https://amireyal.co.il/images/og-image.png"
  meta_og_description = "טיפול פסיכותרפי מקצועי לבוגרים, מתבגרים והדרכת הורים – עמיר אייל."

languageDirection = "rtl"

# **הגדרות קריטיות ליצירת index.json**
[outputs]
  home = ["HTML", "RSS", "JSON"] # וודא ש"JSON" קיים כאן!

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  is="text"
  isPlainText = true
  noUgly = true

# **החלק הזה חסר לך או לא הוגדר נכון - הוא אומר ל-Hugo מה לכלול ב-index.json**
# הוא מגדיר תבנית חדשה בשם 'searchindex' (או כל שם אחר שתבחר)
# שמשתמשת בפורמט 'json' וכוללת את התוכן של כל העמודים.
# לאחר מכן, צריך לקרוא לתבנית הזו באמצעות הפניה ל'searchindex' ב-baseof.html או בקובץ index.html
# כדי ש-Hugo ידע לייצר את הקובץ.
[fuse_index]
  output = "json"
  fields = ["title", "content", "permalink", "tags", "summary"] # השדות שאתה רוצה לכלול באינדקס

[cascade]
  [cascade._target]
    kind = "page" # או "section" אם אתה רוצה לכלול רק סקשנים מסוימים