baseURL = "/"
title = "עמיר אייל פסיכותרפיה מתבגרים, מבוגרים והדרכת הורים"
languageCode = "he"
defaultContentLanguage = "he"
defaultContentLanguageInSubdir = false

[Pagination]
  pagerSize = 10

theme = "mainroad"
disqusShortname = ""
googleAnalytics = ""

[Params]
  description = "הבלוג האישי שלי על כל דבר"
  opengraph = true
  twitter_cards = false
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["posts", "docs"]

 [Params.author]
    name = "עמיר אייל"
    bio = "פסיכותרפיסט מוסמך למתבגרים, מבוגרים והורים"
    avatar = "img/avatar-amir.jpg"

  [Params.logo]
  image = "img/logo.png"        # נתיב לקובץ התמונה של הלוגו בתיקיית static
  title = "פסיכותרפיה למבוגרים, למתבגרים והדרכת הורים"
  subtitle = "כרמיאל והסביבה ואונליין"

  [Params.sidebar]
    home = "left"
    list = "left"
    single = "left"
    widgets = ["search", "recent", "categories", "taglist"]

  [Params.widgets]
    recent_num = 5
    tags_counter = false

   # הוסף כאן את החלק של הגופן:
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Assistant:wght@200;300;400;700&display=swap"
  customCSS = ["css/custom.css"]
  [Params.style.vars]
    highlightColor = "#1e88e5"
    fontFamilyPrimary = "'Assistant', sans-serif"



[languages]
  [languages.he]
    languageName = "עברית"
    weight = 1
    direction = "rtl"
    contentDir = "content"

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-search-fuse-js"

[outputs]
  home = ["HTML", "JSON"]
