backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: 'he'
display_url: https://amireyal5.netlify.app

publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: "posts"
    label: "פוסטים"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{slug}}"
    summary: "{{title}} – {{year}}/{{month}}/{{day}}"
    fields:
      - {label: "כותרת", name: "title", widget: "string"}
      - {label: "תאריך", name: "date", widget: "datetime"}
      - {label: "מחבר", name: "author", widget: "string", default: "עמיר", required: false}
      - {label: "תיאור קצר", name: "description", widget: "text", required: false}
      - {label: "תמונה ראשית", name: "image", widget: "image", required: false, hint: "מופיעה בדף הבית ובראש הפוסט"}
      - {label: "Alt לתמונה", name: "image_alt", widget: "string", required: false}
      - label: "תוכן הפוסט"
        name: "body"
        widget: "markdown"
        modes: ["rich_text", "raw"]
      - {label: "קטגוריות", name: "categories", widget: "list", default: ["כללי"], required: false}
      - {label: "תגיות", name: "tags", widget: "list", required: false}
      - {label: "Meta Title (SEO)", name: "meta_title", widget: "string", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}

  - name: "pages"
    label: "עמודים"
    folder: "content"
    create: true
    filter:
      field: "layout"
      pattern: "page"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    fields:
      - {label: "כותרת", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - label: "תוכן העמוד"
        name: "body"
        widget: "markdown"
        modes: ["rich_text", "raw"]
      - {label: "תבנית", name: "layout", widget: "hidden", default: "page"}
      - {label: "Meta Title (SEO)", name: "meta_title", widget: "string", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
      - {label: "תמונה ראשית", name: "image", widget: "image", required: false}

  - name: "categories"
    label: "קטגוריות"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "שם קטגוריה", name: "title", widget: "string"}
      - {label: "תיאור", name: "description", widget: "text", required: false}
      - {label: "תבנית", name: "layout", widget: "hidden", default: "category"}

  - name: "authors"
    label: "מחברים"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "שם מלא", name: "title", widget: "string"}
      - {label: "ביוגרפיה קצרה", name: "bio", widget: "text", required: false}
      - {label: "תמונה", name: "image", widget: "image", required: false}
      - {label: "תבנית", name: "layout", widget: "hidden", default: "author"}
