backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: he 
site_url: "https://amireyal5.netlify.app/"

publish_mode: editorial_workflow

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "פוסטים"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: "static/uploads/posts/{{slug}}"
    public_folder: "/uploads/posts/{{slug}}"
    path: "{{slug}}/index"
    editor:
      preview: true
    fields:
      - { label: "כותרת", name: "title", widget: "string", required: true }
      - label: "תאריך"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: false
        required: true
        default: ""
      - { label: "מחבר", name: "author", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name"], required: true }
      - { label: "קטגוריות", name: "categories", widget: "list", required: false }
      - { label: "תגיות", name: "tags", widget: "list", required: false }
      - { label: "תמונה ראשית", name: "thumbnail", widget: "image", required: false }
      - { label: "תקציר", name: "summary", widget: "text", required: false }
      - { label: "תוכן", name: "body", widget: "markdown", required: true }
      
      # שדה בחירה לכיוון הסיידבר
      - label: "כיוון סיידבר"
        name: "sidebar"
        widget: "select"
        options:
          - { label: "שמאל", value: "left" }
          - { label: "ימין", value: "right" }
          - { label: "ללא", value: "false" }
        default: "left"
        required: false

      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "כותרת SEO", name: "title", widget: "string", required: false }
          - { label: "תיאור SEO", name: "description", widget: "text", required: false }
          - { label: "מילות מפתח", name: "keywords", widget: "list", required: false }
      - { label: "פוסטים קשורים", name: "related_posts", widget: "relation", collection: "posts", search_fields: ["title"], value_field: "slug", display_fields: ["title"], multiple: true, required: false }
